import type { DisputeIntakeBlocker, DisputeIssueCode, DisputeRequestedOutcome, ParticipantDisputeState } from '@homeservicemarketplace/contracts';
export type CaseLanguage = 'en' | 'ar';
export const DISPUTE_COPY = {
  en: {
    brand: 'FixNow · Support', title: 'Your support cases', introduction: 'A clear record of your booking concern and its review.',
    newCase: 'Report a booking issue', back: 'Back to cases', home: 'Back to application', language: 'العربية', theme: 'Change theme',
    bookingTitle: 'Choose the booking', bookingHint: 'Only bookings you participate in are shown. Eligibility is checked before submission.',
    booking: 'Booking', service: 'Service booking', seeker: 'As a customer', provider: 'As a provider', choose: 'Choose booking',
    listEmpty: 'No support cases yet', listEmptyHint: 'Cases you open, or that involve one of your bookings, will appear here.',
    bookingEmpty: 'No bookings to show', bookingEmptyHint: 'A support case must relate to a booking you participate in.',
    loading: 'Loading…', failed: 'This information could not be loaded. Try again.', denied: 'This case or booking is not available to your account.',
    retry: 'Try again', more: 'Load more', open: 'View case', submitted: 'Submitted', reference: 'Case reference',
    steps: ['The issue', 'Details and outcome', 'Review and submit'], issueTitle: 'What happened?',
    issueHint: 'Choose the closest description. You can explain the details in the next step.',
    detailsTitle: 'Tell us what needs attention', statement: 'Your description',
    statementHint: 'Describe the relevant facts in 20–4,000 characters. Do not include identity documents, payment details or private access codes.',
    outcome: 'What outcome are you requesting?', outcomeHint: 'This is a request for review, not an approved remedy or a payment instruction.',
    reviewTitle: 'Review before sending', privacy: 'Your description is available to you and authorized support staff. It is not automatically shared with the other party in this intake pilot.',
    evidence: 'Attachments are not available in this pilot. Keep relevant evidence securely; do not paste document links or identity details here.',
    unsaved: 'Not sent. Changes are kept only on this page and are lost if you leave or reload.',
    next: 'Continue', previous: 'Previous', submit: 'Submit for review', sending: 'Sending…',
    invalid: 'Complete the required fields before continuing.', submissionFailed: 'Submission was not confirmed. Your text remains here; retry the same request.',
    conflict: 'The booking or policy changed. Refresh eligibility before submitting again.', refresh: 'Refresh eligibility',
    leaveTitle: 'Leave without submitting?', leaveHint: 'Your unsent description is not saved and will be lost.', stay: 'Keep editing', leave: 'Leave page',
    pendingLeave: 'Submission is in progress. Stay on this page until the server responds.',
    timeline: 'Case timeline', nextAction: 'What happens next?', wait: 'Your case is awaiting support review. No response deadline has been assigned yet.',
    contact: 'A case outcome has been recorded. Contact support for the next step; online responses and appeals are not available in this pilot.',
    noNarrative: 'The other party’s private description is not included in this view.', description: 'Your recorded description',
    noPayment: 'A recorded outcome does not confirm that money was refunded or compensation was paid.',
    historyLimit: 'The latest 100 public events are shown.', pilot: 'Limited intake pilot', policy: 'Policy revision',
    openedByYou: 'Opened by you', involvesYou: 'Your booking is involved', statusUpdated: 'Case status updated', decisionRecorded: 'Outcome recorded',
    blocked: {
      NOT_ENABLED: 'Online intake is not enabled for this account. Existing support channels remain available.',
      BOOKING_STATE: 'This booking is not eligible for online intake in its current state.',
      WINDOW_ELAPSED: 'The online reporting window has ended. Contact support for a review of your options.',
      TIMESTAMP_UNAVAILABLE: 'Support must verify the booking date before online intake can proceed.',
      ALREADY_OPEN: 'There is already an open case for this booking. Continue in that case instead of creating another.',
      LEGACY_REVIEW: 'An existing case is being handled by support. Contact support rather than creating a duplicate.',
    } satisfies Record<DisputeIntakeBlocker, string>,
    issues: { SERVICE_QUALITY: 'Service quality', MISSED_APPOINTMENT: 'Missed appointment', SCOPE_DISAGREEMENT: 'Work or scope disagreement', PROPERTY_CONCERN: 'Property concern', COMMUNICATION: 'Communication issue', OTHER: 'Something else' } satisfies Record<DisputeIssueCode, string>,
    outcomes: { CLARIFICATION: 'An explanation', RESCHEDULE: 'Reschedule the service', REPERFORM: 'Revisit or redo the work', PARTIAL_REMEDY: 'A partial remedy', CANCELLATION: 'Review a cancellation', REVIEW: 'Help choosing a fair outcome' } satisfies Record<DisputeRequestedOutcome, string>,
    states: { SUBMITTED: 'Awaiting review', IN_REVIEW: 'Under review', DECISION_RECORDED: 'Outcome recorded', CLOSED: 'Closed' } satisfies Record<ParticipantDisputeState, string>,
  },
  ar: {
    brand: 'FixNow · الدعم', title: 'طلبات الدعم والنزاعات', introduction: 'مسار واضح لتسجيل المشكلة المرتبطة بالحجز ومتابعة مراجعتها.',
    newCase: 'الإبلاغ عن مشكلة في حجز', back: 'العودة إلى الطلبات', home: 'العودة إلى التطبيق', language: 'English', theme: 'تغيير المظهر',
    bookingTitle: 'اختر الحجز', bookingHint: 'تظهر الحجوزات التي تكون طرفاً فيها فقط. يتحقق الخادم من أهلية الطلب قبل الإرسال.',
    booking: 'الحجز', service: 'حجز خدمة', seeker: 'بصفتك مستخدماً', provider: 'بصفتك مهنياً', choose: 'اختيار الحجز',
    listEmpty: 'لا توجد طلبات دعم بعد', listEmptyHint: 'ستظهر هنا الطلبات التي تفتحها أو تتعلق بأحد حجوزاتك.',
    bookingEmpty: 'لا توجد حجوزات لعرضها', bookingEmptyHint: 'يجب أن يتعلق طلب الدعم بحجز تكون طرفاً فيه.',
    loading: 'جارٍ التحميل…', failed: 'تعذر تحميل المعلومات. حاول مرة أخرى.', denied: 'هذا الطلب أو الحجز غير متاح لحسابك.',
    retry: 'إعادة المحاولة', more: 'عرض المزيد', open: 'عرض الطلب', submitted: 'تاريخ الإرسال', reference: 'الرقم المرجعي',
    steps: ['نوع المشكلة', 'التفاصيل والنتيجة', 'المراجعة والإرسال'], issueTitle: 'ما المشكلة التي حدثت؟',
    issueHint: 'اختر الوصف الأقرب. يمكنك توضيح التفاصيل في الخطوة التالية.',
    detailsTitle: 'أخبرنا بما يحتاج إلى مراجعة', statement: 'وصفك للمشكلة',
    statementHint: 'اكتب الوقائع المتعلقة بالمشكلة بين ٢٠ و٤٠٠٠ حرف. لا تكتب بيانات الهوية أو الدفع أو رموز الدخول الخاصة.',
    outcome: 'ما النتيجة التي تطلبها؟', outcomeHint: 'هذا طلب للمراجعة، وليس موافقة على الحل أو أمراً بالدفع.',
    reviewTitle: 'راجع المعلومات قبل الإرسال', privacy: 'يمكنك أنت وموظفو الدعم المخوّلون قراءة وصف المشكلة. لا يُشارك تلقائياً مع الطرف الآخر في هذه النسخة التجريبية.',
    evidence: 'المرفقات غير متاحة في هذه النسخة التجريبية. احتفظ بالأدلة ذات الصلة بأمان، ولا تلصق روابط الوثائق أو بيانات الهوية هنا.',
    unsaved: 'لم يُرسل الطلب. تبقى التعديلات في هذه الصفحة فقط وتُفقد عند مغادرتها أو إعادة تحميلها.',
    next: 'متابعة', previous: 'السابق', submit: 'إرسال للمراجعة', sending: 'جارٍ الإرسال…',
    invalid: 'أكمل الحقول المطلوبة قبل المتابعة.', submissionFailed: 'لم يتأكد إرسال الطلب. النص ما زال هنا؛ أعد محاولة إرسال الطلب نفسه.',
    conflict: 'تغيرت حالة الحجز أو السياسة. حدّث الأهلية قبل إعادة الإرسال.', refresh: 'تحديث الأهلية',
    leaveTitle: 'هل تريد المغادرة دون إرسال؟', leaveHint: 'وصف المشكلة غير المرسل ليس محفوظاً وسيُفقد.', stay: 'متابعة الكتابة', leave: 'مغادرة الصفحة',
    pendingLeave: 'جارٍ إرسال الطلب. ابقَ في الصفحة حتى يصل رد الخادم.',
    timeline: 'سجل متابعة الطلب', nextAction: 'ما الخطوة التالية؟', wait: 'طلبك بانتظار مراجعة الدعم. لم يُحدد موعد للرد بعد.',
    contact: 'تم تسجيل نتيجة للطلب. تواصل مع الدعم لمعرفة الخطوة التالية؛ الرد والاستئناف عبر هذه الصفحة غير متاحين في النسخة التجريبية.',
    noNarrative: 'الوصف الخاص بالطرف الآخر لا يظهر في هذه الصفحة.', description: 'وصفك المسجل',
    noPayment: 'تسجيل نتيجة لا يؤكد تنفيذ استرداد مالي أو دفع تعويض.',
    historyLimit: 'تظهر أحدث ١٠٠ واقعة مسموح بمشاركتها.', pilot: 'نسخة تجريبية محدودة', policy: 'إصدار السياسة',
    openedByYou: 'طلب فتحته أنت', involvesYou: 'طلب يتعلق بحجزك', statusUpdated: 'تحديث حالة الطلب', decisionRecorded: 'تسجيل نتيجة الطلب',
    blocked: {
      NOT_ENABLED: 'الإرسال عبر هذه الصفحة غير مفعّل لحسابك. قنوات الدعم الحالية ما زالت متاحة.',
      BOOKING_STATE: 'حالة الحجز الحالية لا تسمح بفتح طلب عبر هذه الصفحة.',
      WINDOW_ELAPSED: 'انتهت مهلة الإبلاغ عبر هذه الصفحة. تواصل مع الدعم لمراجعة الخيارات المتاحة.',
      TIMESTAMP_UNAVAILABLE: 'يجب أن يتحقق الدعم من تاريخ الحجز قبل السماح بإرسال الطلب.',
      ALREADY_OPEN: 'يوجد طلب مفتوح لهذا الحجز. تابع الطلب الموجود بدلاً من إنشاء طلب آخر.',
      LEGACY_REVIEW: 'يوجد طلب سابق يتابعه الدعم. تواصل مع الدعم بدلاً من إنشاء طلب مكرر.',
    } satisfies Record<DisputeIntakeBlocker, string>,
    issues: { SERVICE_QUALITY: 'جودة الخدمة', MISSED_APPOINTMENT: 'عدم الالتزام بالموعد', SCOPE_DISAGREEMENT: 'اختلاف على العمل المطلوب', PROPERTY_CONCERN: 'مشكلة تتعلق بالممتلكات', COMMUNICATION: 'مشكلة في التواصل', OTHER: 'مشكلة أخرى' } satisfies Record<DisputeIssueCode, string>,
    outcomes: { CLARIFICATION: 'الحصول على توضيح', RESCHEDULE: 'إعادة جدولة الخدمة', REPERFORM: 'إعادة زيارة أو تنفيذ العمل', PARTIAL_REMEDY: 'حل جزئي للمشكلة', CANCELLATION: 'مراجعة الإلغاء', REVIEW: 'المساعدة في اختيار حل مناسب' } satisfies Record<DisputeRequestedOutcome, string>,
    states: { SUBMITTED: 'بانتظار المراجعة', IN_REVIEW: 'قيد المراجعة', DECISION_RECORDED: 'تم تسجيل النتيجة', CLOSED: 'مغلق' } satisfies Record<ParticipantDisputeState, string>,
  },
} as const;
