// Sprint 9B.10 — the provider portfolio contract.
//
//   GET    /v1/me/provider/portfolio
//   POST   /v1/me/provider/portfolio
//   PATCH  /v1/me/provider/portfolio/:itemId
//   POST   /v1/me/provider/portfolio/reorder
//   DELETE /v1/me/provider/portfolio/:itemId
//
// PORTFOLIO MEDIA IS PUBLIC. VERIFICATION EVIDENCE IS RESTRICTED. They share a
// MediaAsset table and NOTHING else: different visibility, different storage
// namespace, different read path, different capability. A portfolio item may
// only ever reference a PUBLIC asset the caller owns, and the server refuses
// rather than trusting the id it is handed — a provider who could attach a
// RESTRICTED evidence asset to a portfolio item would publish their own
// identity documents to the marketplace.

/** Where a portfolio image lives on the public web. */
export interface ProviderPortfolioMedia {
  /** Absolute, renderable in an <img> with no token handshake. */
  url: string;
  contentType: string;
}

export type ProviderPortfolioModerationState = 'PENDING' | 'APPROVED' | 'REJECTED';

export interface ProviderPortfolioItem {
  id: string;
  media: ProviderPortfolioMedia;
  title: string | null;
  description: string | null;
  serviceCategoryId: string | null;
  /** Provider-controlled ordering, ascending. Dense and 0-based after every
   *  mutation, so a client can render by index without gaps. */
  position: number;
  moderationState: ProviderPortfolioModerationState;
  /** Present only when REJECTED, so the provider can act on it. */
  moderationReason: string | null;
  createdAt: string;
}

export interface ProviderPortfolioListResponse {
  items: ProviderPortfolioItem[];
  /** How many more the provider may add. Server-computed from live policy so
   *  the client never re-derives a limit and drifts from it. */
  remainingSlots: number;
  maxItems: number;
}

export interface CreateProviderPortfolioItemRequest {
  /** The key returned by the presign step. NOT a URL: accepting a URL would
   *  mean accepting an arbitrary string and trusting it points at our own
   *  bucket. */
  storageKey: string;
  contentType: string;
  sizeBytes: number;
  title?: string | null;
  description?: string | null;
  serviceCategoryId?: string | null;
  /** The provider asserting they may publish this image — a customer's home
   *  is in it. Required: the schema records the acknowledgement and its
   *  timestamp rather than assuming it silently. */
  publicationRightAck: true;
  // NO idempotencyKey, deliberately. The STORAGE KEY is the idempotency key,
  // and it is a better one than anything a client could generate:
  //
  //   it is server-minted at presign time, so a client cannot vary it;
  //   it is already UNIQUE on MediaAsset, so the database enforces the
  //   guarantee rather than application code remembering to;
  //   a client retrying a create after a network timeout still holds the same
  //   key — which is exactly the case idempotency exists for — whereas a
  //   client-generated token is regenerated by any retry that re-runs the
  //   whole flow.
  //
  // One uploaded file is one portfolio item. Posting the same key twice
  // returns the item that already exists.
}

export interface UpdateProviderPortfolioItemRequest {
  title?: string | null;
  description?: string | null;
  serviceCategoryId?: string | null;
}

export interface ReorderProviderPortfolioRequest {
  /** Every live item id, in the order the provider wants. A complete list
   *  rather than a moved-item delta: a partial reorder has to be reconciled
   *  against a server order the client may not have, and the reconciliation is
   *  where the bugs live. */
  itemIds: string[];
}

export type ReorderProviderPortfolioResponse = ProviderPortfolioListResponse;
