export const ADMIN_OVERVIEW_COPY = {
  en: {
    eyebrow: 'PROVIDER OPERATIONS',
    title: 'Provider applications & approvals',
    description: 'Review the people joining your platform. Inspect their application and evidence before enabling professional work.',
    openQueue: 'Review applications',
    directory: 'All providers',
    policies: 'Verification policies',
    navigation: 'Provider operations',
    pending: 'Awaiting review',
    returned: 'Changes requested',
    drafts: 'Not yet submitted',
    all: 'Registered profiles',
    countsHint: 'Live totals from the provider directory. Drafts have not been submitted for approval.',
    queueTitle: 'Next applications to review',
    queueHint: 'Oldest submissions first. Open a file to review all six registration sections.',
    previewHint: 'Showing up to five applications. Open the queue for search, filters and the complete list.',
    inspect: 'Review application',
    empty: 'No applications awaiting review',
    emptyHint: 'New submissions will appear here. Unsubmitted profiles are available in the provider directory.',
    loading: 'Loading applications…',
    refresh: 'Refresh applications',
    identity: 'Identity',
    workAccess: 'Work access',
    workflowTitle: 'Review before enabling work',
    workflowHint: 'Application approval, identity verification and work access are separate decisions. The server determines which actions are available.',
    workflow: ['Open the submitted application', 'Inspect information and protected evidence', 'Approve or request specific corrections'],
    analytics: 'Platform activity',
  },
  ar: {
    eyebrow: 'إدارة تسجيل المهنيين',
    title: 'طلبات المهنيين والموافقات',
    description: 'راجع ملفات المنضمين إلى منصتك، وتحقق من بيانات التسجيل والوثائق قبل السماح ببدء العمل المهني.',
    openQueue: 'مراجعة طلبات التسجيل',
    directory: 'جميع المهنيين',
    policies: 'سياسات التوثيق',
    navigation: 'إدارة تسجيل المهنيين',
    pending: 'بانتظار المراجعة',
    returned: 'مطلوب تعديل البيانات',
    drafts: 'لم تُرسل بعد',
    all: 'الملفات المسجلة',
    countsHint: 'إجماليات من دليل المهنيين. المسودات لم تُرسل بعد لطلب الموافقة.',
    queueTitle: 'الطلبات التالية للمراجعة',
    queueHint: 'الأقدم إرسالاً أولاً. افتح الملف لمراجعة أقسام التسجيل الستة.',
    previewHint: 'تُعرض خمسة طلبات كحد أقصى. افتح قائمة الطلبات للبحث والتصفية واستعراض الجميع.',
    inspect: 'مراجعة الملف',
    empty: 'لا توجد طلبات بانتظار المراجعة',
    emptyHint: 'ستظهر الطلبات الجديدة هنا بعد إرسالها. تجد الملفات غير المرسلة في دليل المهنيين.',
    loading: 'جارٍ تحميل الطلبات…',
    refresh: 'تحديث الطلبات',
    identity: 'الهوية',
    workAccess: 'صلاحية العمل',
    workflowTitle: 'المراجعة قبل السماح بالعمل',
    workflowHint: 'الموافقة على الطلب وتوثيق الهوية وصلاحية العمل حالات منفصلة. يحدد الخادم الإجراءات المتاحة لكل ملف.',
    workflow: ['فتح نسخة الطلب المرسلة', 'فحص البيانات والوثائق المحمية', 'الموافقة أو طلب تصحيحات محددة'],
    analytics: 'نشاط المنصة',
  },
} as const;
