export const APPROVAL_COPY = {
  en: {
    eyebrow: 'PROVIDER OPERATIONS',
    title: 'Provider approval center',
    description: 'Review applications, verify supporting evidence, and decide who can start working.',
    openQueue: 'Review applications',
    refresh: 'Refresh applications',
    metrics: 'Application overview',
    pending: 'Awaiting review',
    pendingHint: 'Submitted applications',
    draft: 'In progress',
    draftHint: 'Not submitted yet',
    active: 'Active profiles',
    activeHint: 'Not a work-access decision',
    returned: 'Changes requested',
    returnedHint: 'Waiting for the provider',
    queue: 'Next applications to review',
    oldest: 'Oldest submissions first. Open the complete file before deciding.',
    viewAll: 'View the full queue',
    open: 'Review file',
    allProviders: 'All providers',
    loading: 'Loading submitted applications…',
    empty: 'No applications awaiting review',
    emptyHint: 'New submissions will appear here. In-progress registrations remain in the provider directory.',
    unknown: 'Not provided',
    submitted: 'Submitted',
    noDate: 'Submission date unavailable',
    countsHint: 'Counts cover all providers, not just the applications shown below.',
    countUnavailable: '—',
    flowTitle: 'Review before activation',
    flowHint: 'Application approval, identity verification, and work access are separate decisions.',
    flow: [
      {
        title: 'Read the application',
        hint: 'Review all six sections and compare submitted data with current information.',
      },
      {
        title: 'Inspect the evidence',
        hint: 'Review identity documents, specialties, portfolio, and publication rights.',
      },
      {
        title: 'Make a recorded decision',
        hint: 'Approve an eligible application or request specific corrections. The server controls work access.',
      },
    ],
    missingTitle: 'Cannot find a registration?',
    missingHint: 'A saved draft is not a submitted application. Check all providers, then inspect the application and account states.',
    draftsLink: 'View registrations in progress',
    identityLink: 'Identity cases',
    accessAllowed: 'Work access allowed',
    accessBlocked: 'Work access blocked',
    accessUnknown: 'Work access not reported',
  },
  ar: {
    eyebrow: 'إدارة انضمام المهنيين',
    title: 'مركز موافقات المهنيين',
    description: 'راجع طلبات التسجيل والوثائق، ثم اتخذ قرار السماح ببدء العمل.',
    openQueue: 'مراجعة طلبات التسجيل',
    refresh: 'تحديث طلبات التسجيل',
    metrics: 'نظرة عامة على الطلبات',
    pending: 'بانتظار المراجعة',
    pendingHint: 'طلبات تم إرسالها',
    draft: 'قيد الاستكمال',
    draftHint: 'لم تُرسل للمراجعة بعد',
    active: 'الملفات النشطة',
    activeHint: 'لا تعني وحدها السماح بالعمل',
    returned: 'مطلوب تعديل بياناتها',
    returnedHint: 'بانتظار استجابة المهني',
    queue: 'الطلبات التالية للمراجعة',
    oldest: 'الأقدم إرسالاً أولاً. افتح الملف الكامل قبل اتخاذ القرار.',
    viewAll: 'عرض جميع طلبات المراجعة',
    open: 'مراجعة الملف',
    allProviders: 'جميع المهنيين',
    loading: 'جارٍ تحميل طلبات التسجيل…',
    empty: 'لا توجد طلبات بانتظار المراجعة',
    emptyHint: 'ستظهر الطلبات الجديدة هنا بعد إرسالها. التسجيلات غير المكتملة موجودة في دليل المهنيين.',
    unknown: 'غير متوفر',
    submitted: 'أُرسل في',
    noDate: 'تاريخ الإرسال غير متوفر',
    countsHint: 'الأعداد تشمل جميع المهنيين، وليس فقط الطلبات المعروضة أدناه.',
    countUnavailable: '—',
    flowTitle: 'المراجعة قبل بدء العمل',
    flowHint: 'الموافقة على الطلب وتوثيق الهوية وصلاحية العمل حالات مستقلة.',
    flow: [
      {
        title: 'راجع بيانات التسجيل',
        hint: 'افحص الأقسام الستة وقارن البيانات المرسلة بالمعلومات الحالية.',
      },
      {
        title: 'افحص الوثائق والأعمال',
        hint: 'راجع الهوية والتخصصات ومعرض الأعمال وحقوق نشر الصور.',
      },
      {
        title: 'سجّل قرار المراجعة',
        hint: 'وافق على الطلب المستوفي للشروط أو اطلب تصحيحات محددة. الخادم هو من يحدد صلاحية العمل.',
      },
    ],
    missingTitle: 'لا تجد طلب تسجيل؟',
    missingHint: 'حفظ المسودة لا يعني إرسالها للمراجعة. افتح جميع المهنيين وتحقق من حالة الطلب والحساب.',
    draftsLink: 'عرض التسجيلات قيد الاستكمال',
    identityLink: 'ملفات توثيق الهوية',
    accessAllowed: 'مسموح له بالعمل',
    accessBlocked: 'غير مسموح له بالعمل',
    accessUnknown: 'صلاحية العمل غير متوفرة',
  },
} as const;
