import type {
  DisputeWorkspaceAction,
  DisputeWorkspaceState,
} from '@homeservicemarketplace/contracts';
export const WORKSPACE_STATES: Record<'en' | 'ar', Record<DisputeWorkspaceState, string>> = {
  en: {
    GATHERING: 'Gathering information',
    PROPOSED: 'Solution proposed',
    DECIDED: 'Decision recorded',
    APPEALED: 'Independent review',
    CLOSED: 'Closed',
  },
  ar: {
    GATHERING: 'جمع المعلومات',
    PROPOSED: 'حل مقترح',
    DECIDED: 'تم تسجيل القرار',
    APPEALED: 'مراجعة مستقلة',
    CLOSED: 'مغلق',
  },
};
export const ACTION_LABELS: Record<'en' | 'ar', Record<DisputeWorkspaceAction, string>> = {
  en: {
    ASSIGN: 'Assign reviewer',
    REQUEST_INFORMATION: 'Request information',
    RESPOND: 'Add a response',
    PROPOSE: 'Build a solution',
    CONSENT: 'Respond to the solution',
    DECIDE: 'Record a decision',
    APPEAL: 'Request independent review',
    DECIDE_APPEAL: 'Decide the appeal',
    CONFIRM_FULFILMENT: 'Confirm fulfilment',
    CLOSE: 'Close the case',
    HOLD_PRIVATE_TEXT: 'Manage private text retention hold',
    HOLD_EVIDENCE: 'Manage evidence hold',
    REQUEUE_EVIDENCE: 'Retry evidence processing',
    SHARE_REDACTED_EVIDENCE: 'Publish redacted copy',
  },
  ar: {
    ASSIGN: 'تعيين مراجع',
    REQUEST_INFORMATION: 'طلب معلومات',
    RESPOND: 'إضافة رد',
    PROPOSE: 'بناء حل',
    CONSENT: 'الرد على الحل',
    DECIDE: 'تسجيل قرار',
    APPEAL: 'طلب مراجعة مستقلة',
    DECIDE_APPEAL: 'البت في الاستئناف',
    CONFIRM_FULFILMENT: 'تأكيد تنفيذ الالتزام',
    CLOSE: 'إغلاق النزاع',
    HOLD_PRIVATE_TEXT: 'إدارة تعليق محو النصوص الخاصة',
    HOLD_EVIDENCE: 'إدارة تعليق المحو',
    REQUEUE_EVIDENCE: 'إعادة معالجة الدليل',
    SHARE_REDACTED_EVIDENCE: 'نشر النسخة المنقّحة',
  },
};
export const WORKSPACE_COPY = {
  en: {
    title: 'Case workspace',
    subtitle: 'A clear record of the issue, what is needed, and what happens next.',
    queue: 'Dispute review inbox',
    queueHint: 'Prioritize the next action. Open the full case before a decision.',
    reference: 'Case reference',
    refresh: 'Refresh case',
    refreshQueue: 'Refresh queue',
    loading: 'Loading your case…',
    failed: 'The case could not be refreshed. Unsent text is kept; sensitive actions are paused.',
    denied: 'This case is not available to this account.',
    retry: 'Retry',
    back: 'Back to cases',
    all: 'All cases',
    unassigned: 'Unassigned',
    overdue: 'Overdue',
    appeals: 'Appeals',
    summaryEyebrow: 'DISPUTE OPERATIONS',
    summaryDescription:
      'Investigate reported cases, decide with recorded reasons, and hand appeals to an independent reviewer.',
    summaryOpenInbox: 'Open the dispute inbox',
    summaryAllHint: 'Every case you may review',
    summaryUnassignedHint: 'No reviewer has taken these',
    summaryOverdueHint: 'Past the resolution deadline',
    summaryAppealsHint: 'Awaiting an independent reviewer',
    summaryCountsHint:
      'Counts come from the server and cover every case you may review, not only the cases listed below.',
    countUnavailable: 'Unavailable',
    state: 'State',
    mine: 'Assigned to me',
    filter: 'Filter cases',
    saveView: 'Save this filter on this device',
    viewSaved: 'Filter saved on this device. No case details were stored.',
    empty: 'No matching cases',
    emptyHint: 'New eligible cases will appear here. Adjust the filters to see other cases.',
    more: 'Load more',
    open: 'Open case',
    due: 'Response target',
    targetHint: 'This is the policy target, not a guarantee of a decision by this time.',
    assigned: 'Assigned reviewer',
    unassignedHint: 'Waiting for a reviewer to be assigned.',
    youAssigned: 'You are the assigned reviewer',
    otherAssigned: 'Another reviewer is assigned',
    noActions: 'No decision actions are available for this account and case state.',
    next: 'What happens next',
    gather:
      'Respond to requests and add relevant evidence. Your original documents remain private.',
    proposed: 'Read every condition before accepting. A proposal is not a completed action.',
    decided:
      'Read the decision and review window. Confirm only commitments that were actually fulfilled.',
    appealed:
      'A different, authorized reviewer handles this appeal. The original decision is preserved.',
    closed:
      'The case is closed. Its recorded decisions remain available under the applicable policy.',
    process: ['Information', 'Proposed solution', 'Decision', 'Review / appeal', 'Closure'],
    roles: { SEEKER: 'Customer', PROVIDER: 'Provider', REVIEWER: 'Reviewer', SYSTEM: 'System' },
    sections: 'Case sections',
    information: 'Information and replies',
    evidence: 'Private evidence',
    solutions: 'Proposals and decisions',
    history: 'Event timeline',
    facts: 'Verified source records',
    participants: 'Parties',
    tabsHint:
      'Open one section at a time. Reading a section decides nothing: only a recorded command changes the case.',
    tabsSection: 'Section',
    tabsOf: 'of',
    tabsPrevious: 'Previous section',
    tabsNext: 'Next section',
    noAppeals: 'No independent review has been requested for this case.',
    source: 'Source',
    recorded: 'Recorded',
    sourceHint:
      'These are recorded facts, not automatic conclusions. A booking amount is not proof of payment.',
    factsLabels: {
      BOOKING_STATUS: 'Current booking state',
      BOOKED_AMOUNT_NOT_PAYMENT: 'Booked amount — not payment',
      SUBMITTED_AT: 'Application submitted',
    },
    requests: 'Information requested',
    question: 'Question',
    recipient: 'Recipient',
    reply: 'Reply to this request',
    noRequests: 'No information requests are visible to you.',
    requestStates: { OPEN: 'Awaiting response', ANSWERED: 'Answered', EXPIRED: 'Deadline passed' },
    deadline: 'Respond before',
    deadlinePassed:
      'The response deadline has passed. A reviewer can issue a new request; your existing information is not deleted.',
    privateReplies:
      'Your statements and original documents are visible to you and authorized reviewers, not automatically to the other party.',
    statements: 'Statements on your side',
    noStatements: 'No statements are available in this view.',
    text: 'Your response',
    minText:
      'Use 10–4,000 characters. Include relevant facts, not identity numbers or unrelated personal data.',
    upload: 'Add evidence',
    uploadHint:
      'PNG, JPEG or PDF, up to 5 MiB. Uploads are encrypted and cannot be viewed until scanning succeeds.',
    chooseFile: 'Choose a file',
    selectedFile: 'File selected',
    sendFile: 'Upload for scanning',
    uploading: 'Uploading…',
    uploaded: 'Upload received. Scanning is not yet complete.',
    uploadFailed: 'Upload was not confirmed. Keep the same file and retry the same attempt.',
    noEvidence: 'No evidence is visible in this view.',
    private: 'Private original',
    shared: 'Shared redacted copy',
    derivative: 'Unpublished redacted copy',
    view: 'View evidence',
    download: 'Download evidence',
    expires: 'Retention deadline',
    fileType: 'File type',
    fileSize: 'File size',
    hold: 'Hold expiry',
    holdHint:
      'A hold pauses destruction; it does not restore expired access. It cannot reverse an erasure already started.',
    releaseHold: 'Release hold',
    reason: 'Structured reason',
    redact: 'Create a redacted copy',
    redactHint:
      'Remove all unnecessary personal data. This creates a separate PNG; the original is never published.',
    redactedUpload: 'Upload a separately redacted PNG',
    redactedHint:
      'Only a scanned, separately uploaded PNG can be published to both parties. A changed file is not automatically a safe redaction.',
    publishAck:
      'I checked the complete copy and removed identity numbers, private contact details and unrelated personal data.',
    mask: 'Cover a region',
    maskHint:
      'Enter percentage coordinates. The cover is applied to the exported pixels, not a CSS overlay.',
    x: 'From left (%)',
    y: 'From top (%)',
    width: 'Width (%)',
    height: 'Height (%)',
    applyMask: 'Apply cover',
    resetImage: 'Reset image',
    exportRedacted: 'Upload this redacted copy',
    imageFailed: 'The image could not be rendered safely. Use a separately prepared redacted PNG.',
    evidenceStates: {
      PREPARED: 'Upload not complete',
      STORED: 'Awaiting scan',
      SCANNING: 'Scanning',
      SCAN_FAILED: 'Scan unavailable — retry scheduled',
      CLEAN: 'Scan passed',
      QUARANTINED: 'Quarantined — cannot be opened',
      DEAD: 'Processing needs operator review',
      ERASING: 'Erasure in progress',
      ERASURE_FAILED: 'Erasure retry scheduled',
      ERASURE_DEAD: 'Erasure needs operator review',
      ERASED: 'Erasure confirmed',
      EXPIRED: 'Access expired',
    },
    proposal: 'Proposed solution',
    proposalHint:
      'These are service commitments. This workspace does not execute payments, refunds, account sanctions or automatic booking changes.',
    summary: 'Solution summary',
    remedies: 'Commitments and conditions',
    addRemedy: 'Add another commitment',
    remove: 'Remove',
    type: 'Remedy type',
    description: 'What will happen',
    conditions: 'Conditions and responsibilities',
    date: 'Commitment deadline (optional)',
    validUntil: 'Offer valid until',
    accept: 'Accept these terms',
    decline: 'Request a different solution',
    accepted: 'Your acceptance is recorded',
    declined: 'Your decline is recorded',
    responses: 'Acceptances',
    fulfilments: 'Fulfilment confirmations',
    proposalStates: {
      OPEN: 'Open for responses',
      DECLINED: 'Declined',
      SUPERSEDED: 'Replaced by a newer offer',
      DECIDED: 'Linked to a decision',
      EXPIRED: 'Offer expired',
    },
    remedyTypes: {
      CLARIFICATION: 'Clarification',
      RESCHEDULE: 'Reschedule by agreement',
      REPERFORM: 'Repeat the service',
      PARTIAL_REMEDY: 'Partial service remedy',
      CANCELLATION: 'Cancellation arrangement',
      ESCALATION: 'Escalation / higher review',
    },
    decision: 'Recorded decision',
    rationale: 'Explanation shared with both parties',
    rationaleHint:
      'Explain the verified facts and policy. Do not copy private evidence contents, identity numbers or internal notes.',
    policy: 'Policy version',
    basis: 'Event sources used for this decision',
    basisHint: 'Select actual recorded events. No generated assessment is treated as evidence.',
    evidenceUsed: 'Evidence reviewed',
    none: 'None',
    noProposal: 'No agreed proposal',
    noProposalHint:
      'Without an agreed proposal, only an insufficient-basis or independent-review finding is permitted.',
    decisionReasons: {
      AGREED_RESOLUTION: 'Agreed resolution',
      SERVICE_REMEDY: 'Service remedy',
      INSUFFICIENT_BASIS: 'Insufficient basis',
      INDEPENDENT_REVIEW: 'Independent review',
    },
    supersedes: 'Supersedes decision',
    appealBefore: 'Independent review available until',
    appealGrounds: 'Why the decision needs review',
    appealHint:
      'Explain which fact, policy application or evidence needs another review. A different reviewer is required.',
    appealPrivate: 'These grounds are visible to the appellant and authorized reviewers.',
    reviewPending: 'An independent review is pending.',
    originalDecision: 'Original decision',
    newDecision: 'Independent decision',
    noDecisions: 'No decision has been recorded.',
    chooseReviewer: 'Choose an authorized reviewer',
    noReviewers:
      'No eligible reviewer is available. Assign permissions through the existing authorization process; do not bypass them.',
    reviewConfirm:
      'I reviewed the sources, checked for conflicts of interest, and checked that the explanation is safe to share.',
    consentConfirm:
      'I read every commitment, condition and date. My response applies only to this version.',
    fulfilConfirm:
      'The commitments in this recorded solution have actually been fulfilled on my side.',
    closeConfirm:
      'I checked the current decision, review window and both parties’ fulfilment records.',
    cancel: 'Cancel',
    confirm: 'Confirm and record',
    recording: 'Recording…',
    recordedSuccess: 'The server confirmed this action.',
    commandFailed:
      'The action was not confirmed. Your text is kept; retrying unchanged content reuses the same intent.',
    conflict:
      'The case changed. Refresh it and review the current information before submitting again.',
    refreshReview: 'Refresh and review changes',
    invalid: 'Complete all required fields and confirmations.',
    paused: 'Actions are paused while the current file is being refreshed or is unavailable.',
    unsent: 'Text in this dialog is not saved until the server confirms the command.',
    leaveTitle: 'Leave with unsent changes?',
    leaveHint: 'Unsent dialog text will be lost. Submitted records are not affected.',
    stay: 'Stay here',
    leave: 'Leave without sending',
    notifications: 'Case notifications',
    notificationsHint: 'Case records remain available even when notifications are disabled.',
    notificationEnabled: 'Notify me about case updates',
    notificationLanguage: 'Notification language',
    save: 'Save preference',
    draftLoading: 'Loading your saved draft…',
    draftSaved: 'Saved to the server',
    draftSaving: 'Saving…',
    draftDirty: 'Changes not saved yet',
    draftEmpty: 'No draft has been saved yet',
    draftError: 'Draft save was not confirmed. Your text remains here.',
    draftConflict: 'A newer draft exists. Your text has not overwritten it.',
    draftExpiry: 'Draft is retained until',
    reloadDraft: 'Load the saved version',
    reloadDraftHint: 'This replaces unsaved text in this page with the server version.',
    draftEvidence:
      'After submission, you can attach private evidence and respond to information requests.',
    olderEvents: 'Load older events',
    event: 'Case update',
    legacy: 'Earlier support tickets',
    legacyHint:
      'Older tickets use the previous workflow and are not silently converted into new decisions.',
  },
  ar: {
    title: 'مساحة متابعة النزاع',
    subtitle: 'سجل واضح للمشكلة والمعلومات المطلوبة والخطوة التالية.',
    queue: 'صندوق مراجعة النزاعات',
    queueHint: 'ابدأ بالحالات التي تحتاج إجراءً. افتح الملف الكامل قبل اتخاذ قرار.',
    reference: 'الرقم المرجعي',
    refresh: 'تحديث النزاع',
    refreshQueue: 'تحديث القائمة',
    loading: 'جارٍ تحميل النزاع…',
    failed: 'تعذّر تحديث الملف. النص غير المرسل باقٍ، والإجراءات الحساسة متوقفة.',
    denied: 'هذا النزاع غير متاح لهذا الحساب.',
    retry: 'إعادة المحاولة',
    back: 'العودة إلى النزاعات',
    all: 'جميع الحالات',
    unassigned: 'دون مراجع',
    overdue: 'تجاوزت الموعد',
    appeals: 'الاستئنافات',
    summaryEyebrow: 'إدارة النزاعات',
    summaryDescription:
      'افحص الحالات المُبلَّغ عنها، واتّخذ قرارًا بأسباب مُسجَّلة، وأحِل الاستئناف إلى مراجع مستقل.',
    summaryOpenInbox: 'فتح صندوق النزاعات',
    summaryAllHint: 'كل حالة يحقّ لك مراجعتها',
    summaryUnassignedHint: 'لم يتسلّمها أي مراجع',
    summaryOverdueHint: 'تجاوزت موعد الحسم',
    summaryAppealsHint: 'بانتظار مراجع مستقل',
    summaryCountsHint: 'الأعداد من الخادم وتشمل كل حالة يحقّ لك مراجعتها، لا الحالات المعروضة فقط.',
    countUnavailable: 'غير متاح',
    state: 'الحالة',
    mine: 'المعيّنة لي',
    filter: 'تصفية الحالات',
    saveView: 'حفظ هذا الفلتر على الجهاز',
    viewSaved: 'حُفظ الفلتر على الجهاز دون حفظ تفاصيل أي نزاع.',
    empty: 'لا توجد حالات مطابقة',
    emptyHint: 'ستظهر الحالات المؤهلة الجديدة هنا. غيّر الفلتر لعرض حالات أخرى.',
    more: 'تحميل المزيد',
    open: 'فتح النزاع',
    due: 'الموعد المستهدف للرد',
    targetHint: 'هذا موعد السياسة المستهدف، وليس ضماناً لصدور القرار فيه.',
    assigned: 'المراجع المعيّن',
    unassignedHint: 'بانتظار تعيين مراجع.',
    youAssigned: 'أنت المراجع المعيّن',
    otherAssigned: 'الملف معيّن لمراجع آخر',
    noActions: 'لا تتوفر إجراءات قرار لهذا الحساب وحالة النزاع.',
    next: 'ما الخطوة التالية؟',
    gather: 'أجب عن الطلبات وأضف الأدلة المرتبطة بالمشكلة. مستنداتك الأصلية تبقى خاصة.',
    proposed: 'اقرأ الشروط كاملة قبل القبول. اقتراح الحل لا يعني تنفيذه.',
    decided: 'اقرأ القرار ومدة طلب المراجعة. أكّد فقط الالتزامات التي نُفذت فعلياً.',
    appealed: 'يتولى مراجع مخوّل مختلف مراجعة الاستئناف. القرار الأصلي محفوظ.',
    closed: 'أُغلق النزاع، وتبقى القرارات المسجلة متاحة وفق السياسة المطبقة.',
    process: ['المعلومات', 'الحل المقترح', 'القرار', 'المراجعة والاستئناف', 'الإغلاق'],
    roles: { SEEKER: 'العميل', PROVIDER: 'المهني', REVIEWER: 'المراجع', SYSTEM: 'النظام' },
    sections: 'أقسام النزاع',
    information: 'المعلومات والردود',
    evidence: 'الأدلة الخاصة',
    solutions: 'الحلول والقرارات',
    history: 'سجل الأحداث',
    facts: 'وقائع من السجلات',
    participants: 'أطراف النزاع',
    tabsHint:
      'افتح قسماً واحداً في كل مرة. قراءة القسم لا تُقرّر شيئاً؛ لا يتغيّر النزاع إلا بأمر مُسجَّل.',
    tabsSection: 'القسم',
    tabsOf: 'من',
    tabsPrevious: 'القسم السابق',
    tabsNext: 'القسم التالي',
    noAppeals: 'لم يُطلب أي مراجعة مستقلة لهذا النزاع.',
    source: 'المصدر',
    recorded: 'سُجّل في',
    sourceHint: 'هذه وقائع مسجلة وليست استنتاجات آلية. قيمة الحجز ليست إثباتاً للدفع.',
    factsLabels: {
      BOOKING_STATUS: 'حالة الحجز الحالية',
      BOOKED_AMOUNT_NOT_PAYMENT: 'قيمة الحجز — ليست عملية دفع',
      SUBMITTED_AT: 'تاريخ إرسال الطلب',
    },
    requests: 'المعلومات المطلوبة',
    question: 'السؤال',
    recipient: 'الطرف المطلوب منه الرد',
    reply: 'الرد على هذا الطلب',
    noRequests: 'لا توجد طلبات معلومات ظاهرة لك.',
    requestStates: { OPEN: 'بانتظار الرد', ANSWERED: 'تم الرد', EXPIRED: 'انتهت المهلة' },
    deadline: 'آخر موعد للرد',
    deadlinePassed:
      'انتهت مهلة الرد. يستطيع المراجع طلب المعلومات مجدداً، ولا تُحذف المعلومات السابقة.',
    privateReplies:
      'إفاداتك ومستنداتك الأصلية متاحة لك وللمراجعين المخوّلين، ولا تُشارك تلقائياً مع الطرف الآخر.',
    statements: 'الإفادات المتاحة لك',
    noStatements: 'لا توجد إفادات متاحة في هذا العرض.',
    text: 'نص الرد',
    minText:
      'اكتب بين 10 و4,000 حرف. أضف الوقائع المرتبطة بالمشكلة دون أرقام هوية أو بيانات شخصية غير لازمة.',
    upload: 'إضافة دليل',
    uploadHint:
      'صورة PNG أو JPEG أو ملف PDF، حتى 5 ميبيبايت. تُشفّر الملفات ولا تُفتح قبل نجاح الفحص.',
    chooseFile: 'اختيار ملف',
    selectedFile: 'تم اختيار ملف',
    sendFile: 'رفع للفحص',
    uploading: 'جارٍ الرفع…',
    uploaded: 'استُلم الملف، ولم يكتمل فحصه بعد.',
    uploadFailed: 'لم يتأكد الرفع. احتفظ بالملف نفسه وأعد المحاولة.',
    noEvidence: 'لا توجد أدلة ظاهرة في هذا العرض.',
    private: 'أصل خاص',
    shared: 'نسخة منقّحة مشتركة',
    derivative: 'نسخة منقّحة غير منشورة',
    view: 'عرض الدليل',
    download: 'تنزيل الدليل',
    expires: 'موعد انتهاء الاحتفاظ',
    fileType: 'نوع الملف',
    fileSize: 'حجم الملف',
    hold: 'نهاية تعليق المحو',
    holdHint: 'التعليق يوقف الإتلاف ولا يعيد صلاحية فتح ملف منتهٍ. لا يمكنه إيقاف محو بدأ بالفعل.',
    releaseHold: 'رفع تعليق المحو',
    reason: 'السبب المنظم',
    redact: 'إنشاء نسخة منقّحة',
    redactHint: 'أزل البيانات الشخصية غير اللازمة. تُنشأ صورة PNG مستقلة ولا يُنشر الأصل.',
    redactedUpload: 'رفع PNG منقّح بشكل منفصل',
    redactedHint:
      'يمكن نشر نسخة PNG مستقلة بعد فحصها فقط. اختلاف الملف لا يعني تلقائياً أنه منقّح بأمان.',
    publishAck:
      'فحصت النسخة كاملة وأزلت أرقام الهوية وبيانات التواصل الخاصة والبيانات الشخصية غير المرتبطة بالنزاع.',
    mask: 'تغطية منطقة',
    maskHint:
      'أدخل الإحداثيات كنسب مئوية. تُطبق التغطية على الصورة المصدّرة نفسها، وليست طبقة عرض مؤقتة.',
    x: 'من اليسار (%)',
    y: 'من الأعلى (%)',
    width: 'العرض (%)',
    height: 'الارتفاع (%)',
    applyMask: 'تطبيق التغطية',
    resetImage: 'استعادة الصورة الأصلية',
    exportRedacted: 'رفع النسخة المنقّحة',
    imageFailed: 'تعذّر عرض الصورة بأمان. استخدم نسخة PNG منقّحة بشكل منفصل.',
    evidenceStates: {
      PREPARED: 'لم يكتمل الرفع',
      STORED: 'بانتظار الفحص',
      SCANNING: 'جارٍ الفحص',
      SCAN_FAILED: 'الفحص غير متاح — ستعاد المحاولة',
      CLEAN: 'اجتاز الفحص',
      QUARANTINED: 'محجوز — لا يمكن فتحه',
      DEAD: 'المعالجة تحتاج مراجعة المشغّل',
      ERASING: 'جارٍ المحو',
      ERASURE_FAILED: 'ستعاد محاولة المحو',
      ERASURE_DEAD: 'المحو يحتاج مراجعة المشغّل',
      ERASED: 'تم تأكيد المحو',
      EXPIRED: 'انتهت صلاحية الوصول',
    },
    proposal: 'الحل المقترح',
    proposalHint:
      'هذه التزامات خدمية. لا تنفذ هذه المساحة دفعات أو مبالغ مستردة أو عقوبات حساب أو تغييرات حجز آلية.',
    summary: 'ملخص الحل',
    remedies: 'الالتزامات والشروط',
    addRemedy: 'إضافة التزام آخر',
    remove: 'إزالة',
    type: 'نوع الحل',
    description: 'ما الذي سيُنفذ؟',
    conditions: 'الشروط ومسؤوليات الأطراف',
    date: 'موعد تنفيذ الالتزام (اختياري)',
    validUntil: 'العرض صالح حتى',
    accept: 'قبول هذه الشروط',
    decline: 'طلب حل مختلف',
    accepted: 'تم تسجيل قبولك',
    declined: 'تم تسجيل عدم موافقتك',
    responses: 'الموافقات',
    fulfilments: 'تأكيدات التنفيذ',
    proposalStates: {
      OPEN: 'بانتظار رد الأطراف',
      DECLINED: 'غير مقبول',
      SUPERSEDED: 'استُبدل بعرض أحدث',
      DECIDED: 'مرتبط بقرار',
      EXPIRED: 'انتهت صلاحية العرض',
    },
    remedyTypes: {
      CLARIFICATION: 'توضيح',
      RESCHEDULE: 'إعادة جدولة بالاتفاق',
      REPERFORM: 'إعادة تنفيذ الخدمة',
      PARTIAL_REMEDY: 'معالجة خدمية جزئية',
      CANCELLATION: 'ترتيب الإلغاء',
      ESCALATION: 'إحالة لمراجعة أعلى',
    },
    decision: 'القرار المسجل',
    rationale: 'تفسير يُعرض للطرفين',
    rationaleHint:
      'اشرح الوقائع المثبتة والسياسة. لا تنسخ محتويات الأدلة الخاصة أو أرقام الهوية أو الملاحظات الداخلية.',
    policy: 'إصدار السياسة',
    basis: 'الأحداث التي يستند إليها القرار',
    basisHint: 'اختر أحداثاً مسجلة فعلياً. لا يُعتبر التحليل المولّد دليلاً.',
    evidenceUsed: 'الأدلة التي تمت مراجعتها',
    none: 'لا يوجد',
    noProposal: 'دون عرض متفق عليه',
    noProposalHint: 'دون عرض متفق عليه، يُسمح فقط بنتيجة عدم كفاية الأساس أو نتيجة مراجعة مستقلة.',
    decisionReasons: {
      AGREED_RESOLUTION: 'حل متفق عليه',
      SERVICE_REMEDY: 'معالجة خدمية',
      INSUFFICIENT_BASIS: 'عدم كفاية الأساس',
      INDEPENDENT_REVIEW: 'مراجعة مستقلة',
    },
    supersedes: 'يحل محل القرار',
    appealBefore: 'المراجعة المستقلة متاحة حتى',
    appealGrounds: 'لماذا يحتاج القرار إلى مراجعة؟',
    appealHint:
      'وضح الواقعة أو تطبيق السياسة أو الدليل الذي يحتاج مراجعة أخرى. يجب أن يكون المراجع مختلفاً.',
    appealPrivate: 'أسباب الاستئناف متاحة لمقدمه وللمراجعين المخوّلين.',
    reviewPending: 'تجري مراجعة مستقلة.',
    originalDecision: 'القرار الأصلي',
    newDecision: 'قرار المراجعة المستقلة',
    noDecisions: 'لم يُسجّل قرار بعد.',
    chooseReviewer: 'اختر مراجعاً مخوّلاً',
    noReviewers: 'لا يوجد مراجع مؤهل متاح. امنح الصلاحيات عبر نظام التفويض الحالي ولا تتجاوزها.',
    reviewConfirm: 'راجعت المصادر وتحققت من عدم تضارب المصالح ومن سلامة مشاركة التفسير.',
    consentConfirm: 'قرأت كل التزام وشرط وموعد. ردي يتعلق بهذه النسخة فقط.',
    fulfilConfirm: 'نُفذت الالتزامات الواردة في هذا الحل المسجل فعلياً من جانبي.',
    closeConfirm: 'راجعت القرار الحالي ومدة المراجعة وتأكيدات التنفيذ من الطرفين.',
    cancel: 'إلغاء',
    confirm: 'تأكيد وتسجيل',
    recording: 'جارٍ التسجيل…',
    recordedSuccess: 'أكد الخادم تسجيل الإجراء.',
    commandFailed: 'لم يتأكد الإجراء. نصك باقٍ، وإعادة المحاولة دون تغيير تعيد الطلب نفسه.',
    conflict: 'تغيّر النزاع. حدّث الملف وراجع المعلومات الحالية قبل الإرسال مجدداً.',
    refreshReview: 'تحديث ومراجعة التغييرات',
    invalid: 'أكمل الحقول والتأكيدات المطلوبة.',
    paused: 'الإجراءات متوقفة حتى يكتمل تحديث الملف أو يصبح متاحاً.',
    unsent: 'لا يُحفظ نص هذا الحوار حتى يؤكد الخادم الإرسال.',
    leaveTitle: 'المغادرة مع تغييرات غير مرسلة؟',
    leaveHint: 'ستفقد النص غير المرسل في الحوار. السجلات المرسلة لا تتأثر.',
    stay: 'البقاء هنا',
    leave: 'المغادرة دون إرسال',
    notifications: 'إشعارات النزاع',
    notificationsHint: 'تبقى سجلات النزاع متاحة حتى عند تعطيل الإشعارات.',
    notificationEnabled: 'أبلغني بتحديثات النزاعات',
    notificationLanguage: 'لغة الإشعارات',
    save: 'حفظ التفضيل',
    draftLoading: 'جارٍ تحميل المسودة المحفوظة…',
    draftSaved: 'محفوظة على الخادم',
    draftSaving: 'جارٍ الحفظ…',
    draftDirty: 'تغييرات غير محفوظة بعد',
    draftEmpty: 'لم تُحفظ مسودة بعد',
    draftError: 'لم يتأكد حفظ المسودة. نصك باقٍ هنا.',
    draftConflict: 'توجد مسودة أحدث. لم يستبدل نصك بياناتها.',
    draftExpiry: 'تُحفظ المسودة حتى',
    reloadDraft: 'تحميل النسخة المحفوظة',
    reloadDraftHint: 'سيُستبدل النص غير المحفوظ في هذه الصفحة بالنسخة الموجودة على الخادم.',
    draftEvidence: 'بعد الإرسال، يمكنك إرفاق أدلة خاصة والرد على طلبات المعلومات.',
    olderEvents: 'تحميل أحداث أقدم',
    event: 'تحديث النزاع',
    legacy: 'تذاكر الدعم السابقة',
    legacyHint: 'تستخدم التذاكر السابقة المسار القديم، ولا تُحوّل بصمت إلى قرارات جديدة.',
  },
} as const;
export const EVENT_LABELS: Record<'en' | 'ar', Record<string, string>> = {
  en: {
    WORKSPACE_OPENED: 'Case opened',
    ASSIGN: 'Reviewer assigned',
    REQUEST_INFORMATION: 'Information requested',
    RESPOND: 'Response recorded',
    PROPOSE: 'Solution proposed',
    CONSENT: 'Response to solution recorded',
    DECIDE: 'Decision recorded',
    APPEAL: 'Independent review requested',
    DECIDE_APPEAL: 'Independent decision recorded',
    CONFIRM_FULFILMENT: 'Fulfilment confirmed by a party',
    CLOSE: 'Case closed',
    HOLD_PRIVATE_TEXT: 'Private text retention hold updated',
    PRIVATE_TEXT_ERASED: 'Private text erased under the case policy',
    HOLD_EVIDENCE: 'Evidence hold updated',
    REQUEUE_EVIDENCE: 'Evidence processing retried',
    SHARE_REDACTED_EVIDENCE: 'Redacted copy shared',
    EVIDENCE_PREPARED: 'Evidence upload started',
    EVIDENCE_STORED: 'Evidence received for scanning',
    EVIDENCE_SCAN_UPDATED: 'Evidence scan updated',
    EVIDENCE_ERASED: 'Evidence erasure confirmed',
    EVIDENCE_DEAD_LETTER: 'Evidence processing needs review',
    REQUEST_EXPIRED: 'Response deadline passed',
    PROPOSAL_EXPIRED: 'Proposal expired',
  },
  ar: {
    WORKSPACE_OPENED: 'فتح النزاع',
    ASSIGN: 'تعيين مراجع',
    REQUEST_INFORMATION: 'طلب معلومات',
    RESPOND: 'تسجيل رد',
    PROPOSE: 'اقتراح حل',
    CONSENT: 'تسجيل الرد على الحل',
    DECIDE: 'تسجيل قرار',
    APPEAL: 'طلب مراجعة مستقلة',
    DECIDE_APPEAL: 'تسجيل قرار مستقل',
    CONFIRM_FULFILMENT: 'تأكيد التنفيذ من أحد الأطراف',
    CLOSE: 'إغلاق النزاع',
    HOLD_PRIVATE_TEXT: 'تحديث تعليق محو النصوص الخاصة',
    PRIVATE_TEXT_ERASED: 'محو النصوص الخاصة وفق سياسة الملف',
    HOLD_EVIDENCE: 'تحديث تعليق محو الدليل',
    REQUEUE_EVIDENCE: 'إعادة معالجة الدليل',
    SHARE_REDACTED_EVIDENCE: 'مشاركة نسخة منقّحة',
    EVIDENCE_PREPARED: 'بدء رفع دليل',
    EVIDENCE_STORED: 'استلام دليل للفحص',
    EVIDENCE_SCAN_UPDATED: 'تحديث فحص الدليل',
    EVIDENCE_ERASED: 'تأكيد محو الدليل',
    EVIDENCE_DEAD_LETTER: 'معالجة الدليل تحتاج مراجعة',
    REQUEST_EXPIRED: 'انتهاء مهلة الرد',
    PROPOSAL_EXPIRED: 'انتهاء صلاحية العرض',
  },
};
export function translatedLabel(
  map: Readonly<Record<string, string>>,
  key: string,
  fallback: string,
) {
  return map[key] ?? fallback;
}
