export const IDENTITY_PREVIEW_COPY = {
  en: {
    open: 'Inspect document',
    description: 'Inspect the document here. Each opening checks your access and records the read.',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    fit: 'Fit to window',
    rotate: 'Rotate clockwise',
    image: 'Identity document',
    controls: 'Document controls',
    pan: 'Document area. Use the arrow keys to scroll when zoomed in.',
    unavailable: 'The document is unavailable. Access or availability may have changed.',
    unsupported: 'This document cannot be previewed. Download it securely to inspect it.',
    expired: 'This preview has expired. Reopen the document to check access again.',
    sessionExpired: 'Your session has expired. Sign in again to inspect this document.',
    reopen: 'Reopen document',
    previous: 'Previous page',
    next: 'Next page',
    page: (page: number, total: number) => `Page ${page} of ${total}`,
    pdf: 'Document page',
  },
  ar: {
    open: 'فحص الوثيقة',
    description: 'افحص الوثيقة هنا. يُتحقق من صلاحية وصولك ويُسجّل الاطلاع عند كل فتح.',
    zoomIn: 'تكبير',
    zoomOut: 'تصغير',
    fit: 'ملاءمة النافذة',
    rotate: 'تدوير باتجاه عقارب الساعة',
    image: 'وثيقة الهوية',
    controls: 'أدوات فحص الوثيقة',
    pan: 'مساحة الوثيقة. استخدم مفاتيح الأسهم للتمرير بعد التكبير.',
    unavailable: 'الوثيقة غير متاحة. ربما تغيّرت صلاحية الوصول أو إتاحة الوثيقة.',
    unsupported: 'تعذّرت معاينة هذه الوثيقة. يمكنك تنزيلها بأمان لفحصها.',
    expired: 'انتهت مدة المعاينة. أعد فتح الوثيقة للتحقق من صلاحية الوصول مجددًا.',
    sessionExpired: 'انتهت جلستك. سجّل الدخول مجددًا لفحص هذه الوثيقة.',
    reopen: 'إعادة فتح الوثيقة',
    previous: 'الصفحة السابقة',
    next: 'الصفحة التالية',
    page: (page: number, total: number) => `الصفحة ${page} من ${total}`,
    pdf: 'صفحة الوثيقة',
  },
} as const;
