import type { ReviewLanguage } from '../admin-provider-review/copy';

export const DIRECTORY_COPY = {
  en: {
    directory: 'Provider directory',
    queue: 'Review requests',
    directoryEyebrow: 'PROVIDER MANAGEMENT',
    queueEyebrow: 'REVIEW WORKSPACE',
    directoryDescription: 'Follow every provider from registration to working on the marketplace.',
    queueDescription:
      'Inspect the six application steps, check the evidence, then record your decision.',
    openQueue: 'Open review requests',
    openDirectory: 'All providers',
    refresh: 'Refresh',
    matching: 'Matching profiles',
    requestCount: 'Matching requests',
    countsHint: 'Counts follow the search and filters across all result pages.',
    account: 'Account',
    onboarding: 'Onboarding',
    identity: 'Identity',
    portfolio: 'Portfolio',
    access: 'Work access',
    status: 'Application status',
    reviewer: 'Identity reviewer',
    assignment: 'Identity reviewer',
    allReviewers: 'All reviewers',
    unassigned: 'Unassigned',
    assignedToMe: 'Assigned to me',
    noActiveCase: 'No active identity case',
    unknown: 'Not available',
    allIdentity: 'All identity states',
    allPortfolio: 'All portfolio states',
    sort: 'Sort by',
    oldest: 'Oldest submissions first',
    recent: 'Recently updated first',
    advanced: 'More filters',
    country: 'Country code',
    countryHint: 'For example: SY',
    submittedFrom: 'Submitted from',
    submittedTo: 'Submitted through',
    datesTimezone: 'Submission dates use UTC.',
    clear: 'Clear filters',
    searchResults: 'Search results',
    queueOrder: 'Review the oldest requests first',
    queueOrderHint: 'Open a request to inspect its exact submission and approval requirements.',
    directoryOrderHint: 'Account, identity and work access are shown independently.',
    focus: 'Needs attention',
    noAttention: 'Open the profile to inspect the latest details.',
    submitted: 'Submitted',
    submittedUnknown: 'Submission date unavailable',
    notSubmitted: 'Not submitted yet',
    today: 'Less than a day',
    elapsedDays: 'days since submission',
    locationMissing: 'Location incomplete',
    servicesMissing: 'Services not selected',
    loading: 'Loading providers…',
    empty: 'No profiles match these filters.',
    emptyQueue: 'No requests match these filters.',
    emptyQueueHint: 'New applications will appear here after the provider submits them.',
    emptyHint: 'Try another name or email, or clear the filters.',
    open: 'Open profile',
    startReview: 'Review application',
    accountFilter: 'Filtered to one account',
    showAccounts: 'Show all accounts',
    pendingImages: 'awaiting review',
    approvedImages: 'approved',
    rejectedImages: 'returned',
    emptyPortfolio: 'No images',
    canWork: 'Can take work',
    cannotWork: 'Not enabled',
    liveGrant: 'Live work grant',
    noGrant: 'No live work grant',
  },
  ar: {
    directory: 'دليل المهنيين',
    queue: 'طلبات المراجعة',
    directoryEyebrow: 'إدارة المهنيين',
    queueEyebrow: 'مساحة المراجعة',
    directoryDescription: 'تابع كل مهني من التسجيل حتى بدء العمل على المنصة.',
    queueDescription: 'راجع خطوات الطلب الست والوثائق، ثم سجّل قرارك من ملف المهني.',
    openQueue: 'فتح طلبات المراجعة',
    openDirectory: 'جميع المهنيين',
    refresh: 'تحديث',
    matching: 'الملفات المطابقة',
    requestCount: 'الطلبات المطابقة',
    countsHint: 'تعكس الأعداد البحث والفلاتر في جميع صفحات النتائج.',
    account: 'الحساب',
    onboarding: 'طلب الانضمام',
    identity: 'الهوية',
    portfolio: 'معرض الأعمال',
    access: 'صلاحية العمل',
    status: 'حالة الطلب',
    reviewer: 'مراجع الهوية',
    assignment: 'مراجع الهوية',
    allReviewers: 'جميع المراجعين',
    unassigned: 'غير مسند',
    assignedToMe: 'مسند إليّ',
    noActiveCase: 'لا توجد قضية هوية مفتوحة',
    unknown: 'غير متاح',
    allIdentity: 'جميع حالات الهوية',
    allPortfolio: 'جميع حالات المعرض',
    sort: 'الترتيب',
    oldest: 'الأقدم إرسالًا أولًا',
    recent: 'الأحدث تحديثًا أولًا',
    advanced: 'فلاتر إضافية',
    country: 'رمز البلد',
    countryHint: 'مثل: SY',
    submittedFrom: 'أُرسل من تاريخ',
    submittedTo: 'أُرسل حتى تاريخ',
    datesTimezone: 'تواريخ الإرسال حسب التوقيت العالمي UTC.',
    clear: 'مسح الفلاتر',
    searchResults: 'نتائج البحث',
    queueOrder: 'ابدأ بالطلبات الأقدم',
    queueOrderHint: 'افتح الطلب للاطلاع على نسخة الإرسال ومتطلبات الموافقة عليه.',
    directoryOrderHint: 'تظهر حالة الحساب والهوية وصلاحية العمل كلٌّ على حدة.',
    focus: 'يحتاج إلى متابعة',
    noAttention: 'افتح الملف للاطلاع على أحدث التفاصيل.',
    submitted: 'أُرسل',
    submittedUnknown: 'تاريخ الإرسال غير متاح',
    notSubmitted: 'لم يُرسل بعد',
    today: 'أقل من يوم',
    elapsedDays: 'يوم منذ الإرسال',
    locationMissing: 'الموقع غير مكتمل',
    servicesMissing: 'لم تُحدد خدمات',
    loading: 'جارٍ تحميل المهنيين…',
    empty: 'لا توجد ملفات مطابقة للفلاتر.',
    emptyQueue: 'لا توجد طلبات مطابقة للفلاتر.',
    emptyQueueHint: 'ستظهر الطلبات الجديدة هنا بعد أن يرسلها المهنيون.',
    emptyHint: 'جرّب اسمًا أو بريدًا آخر، أو امسح الفلاتر.',
    open: 'فتح الملف',
    startReview: 'مراجعة الطلب',
    accountFilter: 'عرض حساب محدد',
    showAccounts: 'عرض جميع الحسابات',
    pendingImages: 'بانتظار المراجعة',
    approvedImages: 'مقبولة',
    rejectedImages: 'معادة للتعديل',
    emptyPortfolio: 'لا توجد صور',
    canWork: 'يمكنه العمل',
    cannotWork: 'غير مفعّل للعمل',
    liveGrant: 'منحة عمل سارية',
    noGrant: 'لا توجد منحة عمل سارية',
  },
} as const;

export const PROVIDER_STATUS_LABELS: Record<string, Record<ReviewLanguage, string>> = {
  ALL: { en: 'All providers', ar: 'جميع المهنيين' },
  DRAFT: { en: 'Draft', ar: 'مسودة' },
  PENDING_REVIEW: { en: 'Awaiting review', ar: 'بانتظار المراجعة' },
  ACTIVE: { en: 'Accepted', ar: 'مقبول' },
  REJECTED: { en: 'Returned / rejected', ar: 'معاد للتعديل / مرفوض' },
  SUSPENDED: { en: 'Suspended', ar: 'معلّق' },
};

export const ATTENTION_LABELS: Record<string, Record<ReviewLanguage, string>> = {
  ACCOUNT_UNAVAILABLE: { en: 'Resolve the account restriction', ar: 'معالجة قيد الحساب' },
  APPLICATION_NOT_SUBMITTED: {
    en: 'Waiting for the provider to submit',
    ar: 'بانتظار إرسال المهني للطلب',
  },
  APPLICATION_RETURNED: {
    en: 'Waiting for the requested changes',
    ar: 'بانتظار التعديلات المطلوبة',
  },
  IDENTITY_REQUIRED: { en: 'Identity not yet verified', ar: 'الهوية غير موثّقة بعد' },
  IDENTITY_IN_REVIEW: { en: 'Inspect identity evidence', ar: 'فحص مستندات الهوية' },
  IDENTITY_CHANGES_REQUIRED: { en: 'Identity changes requested', ar: 'تعديلات الهوية مطلوبة' },
  PORTFOLIO_REVIEW_REQUIRED: { en: 'Review portfolio images', ar: 'مراجعة صور الأعمال' },
  APPLICATION_REVIEW_REQUIRED: {
    en: 'Review the submitted application',
    ar: 'مراجعة الطلب المُرسل',
  },
};

/** Known additional states; future values degrade to readable unknown copy, never raw codes. */
export const EXTRA_STATE_LABELS: Record<string, Record<ReviewLanguage, string>> = {
  NOT_STARTED: { en: 'Not started', ar: 'لم يبدأ بعد' },
  UNDER_REVIEW: { en: 'Under review', ar: 'قيد المراجعة' },
};

export const ACCESS_REASON_LABELS: Record<string, Record<ReviewLanguage, string>> = {
  ACCOUNT_INELIGIBLE: { en: 'Account unavailable', ar: 'الحساب غير مؤهل' },
  NO_PROVIDER_PROFILE: { en: 'Provider profile missing', ar: 'ملف المهني غير متاح' },
  ONBOARDING_INCOMPLETE: { en: 'Onboarding incomplete', ar: 'طلب الانضمام غير مكتمل' },
  AWAITING_REVIEW: { en: 'Awaiting application review', ar: 'بانتظار مراجعة الطلب' },
  PROVIDER_RESTRICTED: { en: 'Provider restricted', ar: 'المهني مقيّد' },
  PROVIDER_SUSPENDED: { en: 'Provider suspended', ar: 'المهني معلّق' },
  PROVIDER_TERMINATED: { en: 'Provider access terminated', ar: 'أُنهي وصول المهني' },
  VERIFICATION_REQUIRED: { en: 'Identity verification required', ar: 'يلزم توثيق الهوية' },
  NO_WORK_ACCESS: { en: 'Work grant required', ar: 'يلزم منح صلاحية العمل' },
};
