import type { AdminProviderReviewTaskId } from '@homeservicemarketplace/contracts';

export type ReviewLanguage = 'en' | 'ar';
export const TASK_LABELS: Record<ReviewLanguage, Record<AdminProviderReviewTaskId, string>> = {
  en: {
    BASICS_IDENTITY: 'Basics & identity',
    SERVICES_EXPERIENCE: 'Services & experience',
    WORK_AREA: 'Work area',
    WORKING_HOURS: 'Working hours',
    PORTFOLIO: 'Profile & portfolio',
    REVIEW_SUBMISSION: 'Submission & consent',
  },
  ar: {
    BASICS_IDENTITY: 'البيانات والهوية',
    SERVICES_EXPERIENCE: 'الخدمات والخبرة',
    WORK_AREA: 'منطقة العمل',
    WORKING_HOURS: 'أوقات العمل',
    PORTFOLIO: 'الملف ومعرض الأعمال',
    REVIEW_SUBMISSION: 'الطلب والموافقة',
  },
};

export const REVIEW_COPY = {
  en: {
    back: 'Back to providers',
    eyebrow: 'PROVIDER REVIEW',
    title: 'Application review',
    refresh: 'Refresh',
    submitted: 'Submitted application',
    current: 'Current profile',
    sourceHint: 'Review the information captured when this application was submitted.',
    currentHint:
      'Current profile information may differ from the submitted application. Decisions remain linked to the submission.',
    historicalMissing:
      'This older application does not contain a complete review snapshot. Its historical fields cannot be reconstructed. You can inspect the current profile separately.',
    noSubmission:
      'This provider has not submitted an application yet. Their current saved profile is available below.',
    notCaptured: 'Not captured in this submission',
    notProvided: 'Not provided',
    empty: 'Nothing added yet',
    loading: 'Loading the provider application…',
    failed: 'We could not load this application.',
    forbidden: 'You do not have permission to view this provider review.',
    notFound: 'This provider review is not available.',
    retry: 'Try again',
    account: 'Account',
    application: 'Application',
    identity: 'Identity verification',
    access: 'Work access',
    allowed: 'Can take work',
    blocked: 'Not enabled',
    reviewPanel: 'Review decision',
    decisionHint: 'Check the application, identity evidence and services before making a decision.',
    ready: 'Ready for your decision',
    blockers: 'Approval prerequisites',
    approve: 'Approve application',
    requestChanges: 'Request changes',
    noActions: 'No review action is available for your account on this application.',
    privateNote: 'Internal review note',
    privateHint: 'Visible to authorized administrators only. Never sent to the provider.',
    privatePlaceholder: 'Add context for the review team…',
    confirmApproval: 'Approve this application?',
    confirmApprovalHint:
      'The server will recheck the submitted information, identity and service requirements, record your decision and update the provider’s access where eligible.',
    confirmChanges: 'Send these changes to the provider?',
    confirmChangesHint:
      'The provider will see these instructions and can update the selected tasks before submitting again.',
    confirm: 'Confirm decision',
    cancel: 'Cancel',
    saving: 'Recording decision…',
    decisionSuccess: 'Your decision has been recorded.',
    conflict:
      'This application changed while you were reviewing it. Your unsent notes and instructions are preserved. Refresh, inspect the changes and confirm again.',
    mutationFailed: 'The decision could not be recorded. Your input has been kept.',
    task: 'Task to update',
    field: 'Field (optional)',
    fieldPlaceholder: 'For example: phoneNumber',
    reason: 'Reason',
    providerMessage: 'Instruction for the provider',
    messageHint: 'Explain exactly what needs to change. This message is visible to the provider.',
    messagePlaceholder: 'Tell the provider what to update and why…',
    addCorrection: 'Add another correction',
    remove: 'Remove correction',
    messageRequired: 'Write an instruction for every requested correction.',
    reasonRequired: 'Choose a reason.',
    name: 'Display name',
    providerType: 'Provider type',
    business: 'Business name',
    email: 'Email',
    phone: 'Phone',
    proven: 'Verified',
    unproven: 'Not verified',
    individual: 'Individual',
    registeredBusiness: 'Business',
    experience: 'Years of experience',
    professionSince: 'Working since',
    equipment: 'Equipment',
    transport: 'Transport',
    primaryService: 'Primary service',
    services: 'Selected services',
    country: 'Country',
    city: 'City',
    radius: 'Service radius',
    workshop: 'Workshop address',
    selectedAreas: 'Selected service areas',
    areasSelected: 'areas selected',
    timezone: 'Timezone',
    hours: 'Weekly availability',
    closed: 'Unavailable',
    headline: 'Public headline',
    bio: 'About the provider',
    additional: 'Additional information',
    gallery: 'Portfolio review',
    galleryHint:
      'Portfolio is optional. Review each image for publication independently of identity verification.',
    galleryEmpty: 'No portfolio images. An empty gallery does not block the application.',
    galleryHistoric:
      'These are the portfolio details captured with the application. Live moderation is shown below.',
    galleryCurrent: 'Current portfolio moderation',
    imageUnavailable: 'Image not available',
    openImage: 'Inspect image',
    approveImage: 'Approve image',
    rejectImage: 'Reject image',
    imageReason: 'Reason shown to the provider',
    imageReasonRequired: 'Explain why this image needs to be changed.',
    mediaFailed: 'The image could not be opened.',
    categoryReview: 'Service requests',
    categoryHint:
      'Each requested service needs its own review. Approving the application does not approve services automatically.',
    approveService: 'Approve service',
    rejectService: 'Reject service',
    confirmService: 'Confirm service decision',
    evidence: 'Identity evidence',
    evidenceHint: 'Restricted documents are opened through an authorized, audited download.',
    noEvidence: 'No identity verification case has been submitted.',
    evidenceDenied: 'Your account cannot open restricted identity documents.',
    download: 'Download securely',
    unavailable: 'Not available to open',
    evidenceFailed: 'The document could not be opened. Access may have changed.',
    documents: 'documents',
    requirements: 'Evidence requirements',
    satisfied: 'Received',
    outstanding: 'Outstanding',
    submittedAt: 'Submitted on',
    capturedAt: 'Captured on',
    policyVersion: 'Review policy',
    consentVersion: 'Accepted terms',
    consentAt: 'Consent recorded',
    noConsent: 'No consent recorded',
    applicationDecision: 'Application decision',
    history: 'Review history',
    historyEmpty: 'No decision has been recorded.',
    previousCorrections: 'Changes requested from the provider',
    capabilities: 'Current permissions',
    capabilityHint: 'Effective permissions are calculated by the server.',
    viewMarketplace: 'View marketplace',
    submitBid: 'Send offers',
    manageBookings: 'Manage bookings',
    viewEarnings: 'View earnings',
    allowedCapability: 'Allowed',
    deniedCapability: 'Unavailable',
    reasonDocument: 'Documents complete and legible',
    reasonMissing: 'Information missing',
    reasonIncorrect: 'Information needs correction',
    reasonUnclear: 'Information unclear',
    reasonOther: 'Other',
    photo: 'Profile photo',
    order: 'Item',
    revision: 'Revision',
    moderation: 'Moderation',
    refreshBeforeAction: 'Refresh the application before making another decision.',
    noHistory: 'Not decided',
    protected: 'Restricted',
    portfolioSuccess: 'Portfolio decision recorded.',
    serviceSuccess: 'Service decision recorded.',
    currentOnly: 'Current state',
    verifiedEvidence: 'Identity evidence decision',
    identityCaseState: 'Verification case',
    caseAction: 'Review identity case',
    requiresReason: 'Choose a reason to continue.',
    caseApproved: 'Identity decision recorded.',
    caseReason: 'Identity review reason',
    noDocumentHistory: 'No identity decision recorded.',
    viewDetails: 'View details',
    close: 'Close',
    publicationAck: 'Publication consent',
    snapshotItems: 'Submitted portfolio',
    servicesNone: 'No services selected',
    requestChangesSummary:
      'Changes are linked to the selected tasks so the provider can return directly to them.',
  },
  ar: {
    back: 'العودة إلى المهنيين',
    eyebrow: 'مراجعة المهني',
    title: 'مراجعة طلب الانضمام',
    refresh: 'تحديث',
    submitted: 'الطلب المُرسل',
    current: 'الملف الحالي',
    sourceHint: 'راجع المعلومات المحفوظة لحظة إرسال هذا الطلب.',
    currentHint: 'قد تختلف بيانات الملف الحالية عن الطلب المُرسل. يبقى القرار مرتبطًا بالطلب.',
    historicalMissing:
      'هذا الطلب القديم لا يحتوي على نسخة مراجعة كاملة. لا يمكن استعادة الحقول التي لم تُحفظ حينها. يمكنك الاطلاع على الملف الحالي بصورة منفصلة.',
    noSubmission: 'لم يُرسل هذا المهني طلبًا للمراجعة بعد. تظهر أدناه بياناته الحالية المحفوظة.',
    notCaptured: 'لم يُحفظ في هذا الطلب',
    notProvided: 'لم يُضف',
    empty: 'لا توجد بيانات بعد',
    loading: 'جارٍ تحميل طلب المهني…',
    failed: 'تعذّر تحميل هذا الطلب.',
    forbidden: 'ليست لديك صلاحية للاطلاع على مراجعة هذا المهني.',
    notFound: 'مراجعة هذا المهني غير متاحة.',
    retry: 'حاول مجددًا',
    account: 'الحساب',
    application: 'طلب الانضمام',
    identity: 'توثيق الهوية',
    access: 'صلاحية العمل',
    allowed: 'يمكنه بدء العمل',
    blocked: 'غير مفعّلة',
    reviewPanel: 'قرار المراجعة',
    decisionHint: 'راجع بيانات الطلب ووثائق الهوية والخدمات قبل اتخاذ القرار.',
    ready: 'جاهز لاتخاذ القرار',
    blockers: 'متطلبات الموافقة',
    approve: 'الموافقة على الطلب',
    requestChanges: 'طلب تعديلات',
    noActions: 'لا يتوفر إجراء مراجعة لحسابك على هذا الطلب.',
    privateNote: 'ملاحظة داخلية للمراجعة',
    privateHint: 'تظهر للمسؤولين المخوّلين فقط، ولا تُرسل إلى المهني.',
    privatePlaceholder: 'أضف ملاحظة لفريق المراجعة…',
    confirmApproval: 'هل توافق على هذا الطلب؟',
    confirmApprovalHint:
      'سيعيد النظام فحص بيانات الطلب والهوية ومتطلبات الخدمات، ثم يسجل قرارك ويحدّث صلاحيات المهني عند استيفاء الشروط.',
    confirmChanges: 'هل ترسل هذه التعديلات إلى المهني؟',
    confirmChangesHint: 'ستظهر هذه التعليمات للمهني ليعدّل المهام المحددة ثم يعيد إرسال الطلب.',
    confirm: 'تأكيد القرار',
    cancel: 'إلغاء',
    saving: 'جارٍ تسجيل القرار…',
    decisionSuccess: 'تم تسجيل قرارك.',
    conflict:
      'تغيّر الطلب أثناء مراجعته. احتفظنا بالملاحظات والتعليمات التي لم تُرسل. حدّث البيانات وراجع التغييرات ثم أكّد القرار مجددًا.',
    mutationFailed: 'تعذّر تسجيل القرار. احتفظنا بما كتبته.',
    task: 'المهمة المطلوب تعديلها',
    field: 'الحقل (اختياري)',
    fieldPlaceholder: 'مثلاً: phoneNumber',
    reason: 'السبب',
    providerMessage: 'تعليمات للمهني',
    messageHint: 'وضح بدقة ما يجب تعديله. تظهر هذه الرسالة للمهني.',
    messagePlaceholder: 'اشرح للمهني ما الذي يحتاج إلى تعديل ولماذا…',
    addCorrection: 'إضافة تعديل آخر',
    remove: 'حذف التعديل',
    messageRequired: 'اكتب تعليمات لكل تعديل مطلوب.',
    reasonRequired: 'اختر السبب.',
    name: 'الاسم الظاهر',
    providerType: 'نوع المهني',
    business: 'اسم المنشأة',
    email: 'البريد الإلكتروني',
    phone: 'رقم الهاتف',
    proven: 'مؤكد',
    unproven: 'غير مؤكد',
    individual: 'فرد',
    registeredBusiness: 'منشأة',
    experience: 'سنوات الخبرة',
    professionSince: 'بداية العمل بالمهنة',
    equipment: 'المعدات',
    transport: 'وسائل التنقل',
    primaryService: 'الخدمة الرئيسية',
    services: 'الخدمات المختارة',
    country: 'الدولة',
    city: 'المدينة',
    radius: 'نطاق الخدمة',
    workshop: 'عنوان الورشة',
    selectedAreas: 'مناطق الخدمة المختارة',
    areasSelected: 'مناطق مختارة',
    timezone: 'المنطقة الزمنية',
    hours: 'جدول العمل الأسبوعي',
    closed: 'غير متاح',
    headline: 'العنوان المهني',
    bio: 'نبذة عن المهني',
    additional: 'معلومات إضافية',
    gallery: 'مراجعة معرض الأعمال',
    galleryHint: 'معرض الأعمال اختياري. تُراجع كل صورة للنشر بصورة مستقلة عن توثيق الهوية.',
    galleryEmpty: 'لا توجد صور أعمال. غياب المعرض لا يمنع الموافقة على الطلب.',
    galleryHistoric: 'هذه بيانات المعرض المحفوظة مع الطلب. تظهر المراجعة الحالية أدناه.',
    galleryCurrent: 'المراجعة الحالية لمعرض الأعمال',
    imageUnavailable: 'الصورة غير متاحة',
    openImage: 'فحص الصورة',
    approveImage: 'قبول الصورة',
    rejectImage: 'رفض الصورة',
    imageReason: 'سبب يظهر للمهني',
    imageReasonRequired: 'اشرح سبب الحاجة إلى تغيير هذه الصورة.',
    mediaFailed: 'تعذّر فتح الصورة.',
    categoryReview: 'طلبات الخدمات',
    categoryHint:
      'تحتاج كل خدمة مطلوبة إلى مراجعة مستقلة. الموافقة على طلب الانضمام لا توافق على الخدمات تلقائيًا.',
    approveService: 'قبول الخدمة',
    rejectService: 'رفض الخدمة',
    confirmService: 'تأكيد قرار الخدمة',
    evidence: 'وثائق الهوية',
    evidenceHint: 'تُفتح الوثائق الحساسة عبر تنزيل مخوّل ومسجل في سجل التدقيق.',
    noEvidence: 'لم يُرسل طلب توثيق هوية بعد.',
    evidenceDenied: 'لا يملك حسابك صلاحية فتح وثائق الهوية الحساسة.',
    download: 'تنزيل آمن',
    unavailable: 'غير متاح للفتح',
    evidenceFailed: 'تعذّر فتح الوثيقة. ربما تغيّرت صلاحية الوصول.',
    documents: 'وثائق',
    requirements: 'الوثائق المطلوبة',
    satisfied: 'مستلمة',
    outstanding: 'مطلوبة',
    submittedAt: 'تاريخ إرسال الطلب',
    capturedAt: 'تاريخ حفظ النسخة',
    policyVersion: 'سياسة المراجعة',
    consentVersion: 'الشروط المقبولة',
    consentAt: 'تاريخ الموافقة',
    noConsent: 'لا توجد موافقة مسجلة',
    applicationDecision: 'قرار طلب الانضمام',
    history: 'سجل المراجعة',
    historyEmpty: 'لم يُسجل قرار بعد.',
    previousCorrections: 'تعديلات طُلبت من المهني',
    capabilities: 'الصلاحيات الحالية',
    capabilityHint: 'يحسب النظام الصلاحيات الفعلية.',
    viewMarketplace: 'استعراض السوق',
    submitBid: 'تقديم العروض',
    manageBookings: 'إدارة الحجوزات',
    viewEarnings: 'عرض الأرباح',
    allowedCapability: 'مسموح',
    deniedCapability: 'غير متاح',
    reasonDocument: 'الوثائق كاملة وواضحة',
    reasonMissing: 'معلومات ناقصة',
    reasonIncorrect: 'معلومات تحتاج إلى تصحيح',
    reasonUnclear: 'معلومات غير واضحة',
    reasonOther: 'سبب آخر',
    photo: 'الصورة الشخصية',
    order: 'عنصر',
    revision: 'الإصدار',
    moderation: 'المراجعة',
    refreshBeforeAction: 'حدّث الطلب قبل اتخاذ قرار جديد.',
    noHistory: 'لم يُتخذ قرار',
    protected: 'محمي',
    portfolioSuccess: 'تم تسجيل قرار مراجعة الصورة.',
    serviceSuccess: 'تم تسجيل قرار الخدمة.',
    currentOnly: 'الحالة الحالية',
    verifiedEvidence: 'قرار توثيق الهوية',
    identityCaseState: 'طلب التوثيق',
    caseAction: 'مراجعة طلب توثيق الهوية',
    requiresReason: 'اختر السبب للمتابعة.',
    caseApproved: 'تم تسجيل قرار الهوية.',
    caseReason: 'سبب قرار توثيق الهوية',
    noDocumentHistory: 'لم يُسجل قرار بشأن الهوية.',
    viewDetails: 'عرض التفاصيل',
    close: 'إغلاق',
    publicationAck: 'الموافقة على النشر',
    snapshotItems: 'المعرض عند إرسال الطلب',
    servicesNone: 'لم تُحدد خدمات',
    requestChangesSummary: 'ترتبط التعديلات بالمهام المحددة ليتمكن المهني من العودة إليها مباشرة.',
  },
} as const;

const STATUS_LABELS: Record<ReviewLanguage, Record<string, string>> = {
  en: {
    ACTIVE: 'Active',
    NORMAL: 'Good standing',
    GOOD: 'Good standing',
    CONTENT_UPDATED: 'Content updated',
    SUSPENDED: 'Suspended',
    LOCKED: 'Locked',
    DELETED: 'Deleted',
    PENDING_VERIFICATION: 'Verification pending',
    DRAFT: 'Draft',
    IN_PROGRESS: 'In progress',
    PENDING_REVIEW: 'Awaiting review',
    AWAITING_REVIEW: 'Awaiting review',
    SUBMITTED: 'Submitted',
    IN_REVIEW: 'In review',
    ACTION_REQUIRED: 'Changes needed',
    DOCUMENTS_REQUIRED: 'Documents required',
    ACCEPTED: 'Accepted',
    RETURNED: 'Returned for changes',
    VERIFIED: 'Verified',
    UNVERIFIED: 'Not verified',
    REJECTED: 'Rejected',
    APPROVED: 'Approved',
    PENDING: 'Pending review',
    EXPIRED: 'Expired',
    RESTRICTED: 'Restricted',
    TERMINATED: 'Terminated',
    CLEAN: 'Safety check passed',
    QUARANTINED: 'Quarantined',
    SCAN_FAILED: 'Safety check failed',
    ON_FOOT: 'On foot',
    MOTORCYCLE: 'Motorcycle',
    CAR: 'Car',
    VAN: 'Van',
    TRUCK: 'Truck',
    PUBLIC_TRANSPORT: 'Public transport',
  },
  ar: {
    ACTIVE: 'نشط',
    NORMAL: 'وضع سليم',
    GOOD: 'وضع سليم',
    CONTENT_UPDATED: 'تم تحديث المحتوى',
    SUSPENDED: 'معلّق',
    LOCKED: 'مقفل',
    DELETED: 'محذوف',
    PENDING_VERIFICATION: 'بانتظار التحقق',
    DRAFT: 'مسودة',
    IN_PROGRESS: 'قيد الإكمال',
    PENDING_REVIEW: 'بانتظار المراجعة',
    AWAITING_REVIEW: 'بانتظار المراجعة',
    SUBMITTED: 'مُرسل',
    IN_REVIEW: 'قيد المراجعة',
    ACTION_REQUIRED: 'يحتاج إلى تعديلات',
    DOCUMENTS_REQUIRED: 'الوثائق مطلوبة',
    ACCEPTED: 'مقبول',
    RETURNED: 'أُعيد للتعديل',
    VERIFIED: 'موثّق',
    UNVERIFIED: 'غير موثّق',
    REJECTED: 'مرفوض',
    APPROVED: 'مقبول',
    PENDING: 'بانتظار المراجعة',
    EXPIRED: 'منتهي الصلاحية',
    RESTRICTED: 'مقيّد',
    TERMINATED: 'منتهي',
    CLEAN: 'اجتاز فحص الأمان',
    QUARANTINED: 'محجور',
    SCAN_FAILED: 'تعذّر فحص الأمان',
    ON_FOOT: 'مشيًا',
    MOTORCYCLE: 'دراجة نارية',
    CAR: 'سيارة',
    VAN: 'شاحنة صغيرة',
    TRUCK: 'شاحنة',
    PUBLIC_TRANSPORT: 'النقل العام',
  },
};
export function statusLabel(value: string | null | undefined, lang: ReviewLanguage): string {
  return value ? (STATUS_LABELS[lang][value] ?? value) : REVIEW_COPY[lang].notProvided;
}
export const BLOCKER_LABELS: Record<ReviewLanguage, Record<string, string>> = {
  en: {
    SELF_REVIEW: 'You cannot review your own application.',
    PERMISSION_REQUIRED: 'Review permission is required.',
    ACCOUNT_INELIGIBLE: 'The account is not eligible for work.',
    PROVIDER_RESTRICTED: 'A provider restriction must be resolved.',
    NOT_SUBMITTED: 'No application has been submitted.',
    SUBMISSION_ALREADY_DECIDED: 'This submission already has a decision.',
    SNAPSHOT_UNAVAILABLE: 'A complete submitted snapshot is required.',
    SUBMITTED_CONTENT_CHANGED:
      'The profile changed after submission. Request an updated application.',
    CATEGORY_REVIEW_REQUIRED: 'Review the pending service requests.',
    NO_APPROVED_SPECIALTY: 'At least one approved service is required.',
    VERIFICATION_REQUIRED: 'Identity verification is required.',
    EVIDENCE_NOT_READY: 'Required identity evidence is not ready for review.',
    WORK_GRANT_REQUIRED: 'A work-access grant is required.',
  },
  ar: {
    SELF_REVIEW: 'لا يمكنك مراجعة طلبك الشخصي.',
    PERMISSION_REQUIRED: 'تحتاج إلى صلاحية المراجعة.',
    ACCOUNT_INELIGIBLE: 'الحساب غير مؤهل للعمل.',
    PROVIDER_RESTRICTED: 'يجب معالجة القيد المفروض على المهني.',
    NOT_SUBMITTED: 'لم يُرسل طلب للمراجعة.',
    SUBMISSION_ALREADY_DECIDED: 'صدر قرار بشأن هذا الطلب مسبقًا.',
    SNAPSHOT_UNAVAILABLE: 'يلزم وجود نسخة كاملة من الطلب المُرسل.',
    SUBMITTED_CONTENT_CHANGED:
      'تغيّرت البيانات بعد إرسال الطلب. اطلب من المهني تحديث الطلب وإرساله مجددًا.',
    CATEGORY_REVIEW_REQUIRED: 'راجع طلبات الخدمات المعلّقة.',
    NO_APPROVED_SPECIALTY: 'يلزم اعتماد خدمة واحدة على الأقل.',
    VERIFICATION_REQUIRED: 'يلزم توثيق الهوية.',
    EVIDENCE_NOT_READY: 'وثائق الهوية المطلوبة غير جاهزة للمراجعة.',
    WORK_GRANT_REQUIRED: 'يلزم منح صلاحية العمل.',
  },
};
