// Sprint 9B.18 — the professional title, suggested and never assumed.
//
// A provider who has told us they lead with plumbing should not then have to
// invent the words "Plumber" from nothing in a box with no example in it. So
// the primary specialty produces a SUGGESTION.
//
// WHAT A SUGGESTION IS NOT
//
// It is not the title. Nothing here writes to the profile, and no caller may
// treat the return value as published copy: the provider reads it, edits it if
// they like it, and the public-profile task is where it is finally written.
// Auto-publishing would put words in someone's mouth on the surface customers
// judge them by — and would do it in a language they may not have chosen.
//
// WHY A DETERMINISTIC MAPPING RATHER THAN A MODEL OR A TABLE
//
// Two clients and one server must agree on what a category is called, in two
// languages, without a round trip and without drifting. A pure function keyed
// by the catalogue's own stable slug does that, is testable without a
// database, and produces the same words on every surface. The catalogue's
// `labelEn`/`labelAr` are the fallback for any slug not named here — so a
// category added tomorrow suggests something reasonable rather than nothing.

export type TitleLang = 'en' | 'ar';

/**
 * Trade names, keyed by the catalogue slug.
 *
 * A trade name is not the category label: the category is "Plumbing", the
 * person is a "Plumber". Arabic is not a translation of the English here — it
 * is the word the trade is actually called, which is why both are written out
 * rather than generated by appending a suffix.
 */
const TRADE_TITLES: Record<string, { en: string; ar: string }> = {
  plumbing: { en: 'Plumber', ar: 'سبّاك' },
  electrical: { en: 'Electrician', ar: 'كهربائي' },
  carpentry: { en: 'Carpenter', ar: 'نجّار' },
  painting: { en: 'Painter', ar: 'دهّان' },
  cleaning: { en: 'Cleaner', ar: 'عامل تنظيف' },
  'air-conditioning': { en: 'AC Technician', ar: 'فنّي تكييف' },
  appliance_repair: { en: 'Appliance Technician', ar: 'فنّي أجهزة منزلية' },
  'appliance-repair': { en: 'Appliance Technician', ar: 'فنّي أجهزة منزلية' },
  masonry: { en: 'Mason', ar: 'بنّاء' },
  welding: { en: 'Welder', ar: 'حدّاد' },
  gardening: { en: 'Gardener', ar: 'بستاني' },
  moving: { en: 'Mover', ar: 'عامل نقل' },
  'pest-control': { en: 'Pest Control Technician', ar: 'فنّي مكافحة حشرات' },
  satellite: { en: 'Satellite Technician', ar: 'فنّي ستالايت' },
  glass: { en: 'Glazier', ar: 'فنّي زجاج' },
  flooring: { en: 'Flooring Installer', ar: 'فنّي أرضيات' },
};

export interface TitleSuggestionInput {
  /** The primary specialty's catalogue slug. */
  slug: string;
  /** The catalogue's own labels, used when the slug has no trade name yet. */
  labelEn: string;
  labelAr: string;
  lang: TitleLang;
}

/**
 * The suggested title for a primary specialty.
 *
 * Deterministic and total: every input produces something a human can read,
 * because a picker that offers an empty suggestion is worse than one that
 * offers none.
 */
export function suggestProfessionalTitle(input: TitleSuggestionInput): string {
  const trade = TRADE_TITLES[input.slug];
  if (trade) return input.lang === 'ar' ? trade.ar : trade.en;

  // No trade name for this slug. The catalogue label is the honest fallback —
  // "Flooring" rather than a guessed "Flooring-er", and never an English word
  // handed to an Arabic reader.
  return (input.lang === 'ar' ? input.labelAr : input.labelEn).trim();
}

/** Exported for the test that asserts every seeded slug has a trade name, and
 *  for an admin surface that may later want to show the gaps. */
export function knownTitleSlugs(): string[] {
  return Object.keys(TRADE_TITLES);
}

// ─── Validation ─────────────────────────────────────────────────────────────
//
// A title is rendered next to a provider's name wherever customers see them.
// These rules exist because the box is free text and the surface is public.

export const TITLE_MIN_LENGTH = 2;
export const TITLE_MAX_LENGTH = 60;

export type TitleRefusal =
  | 'TOO_SHORT'
  | 'TOO_LONG'
  | 'CONTAINS_URL'
  | 'CONTAINS_CONTACT'
  | 'PROHIBITED_CLAIM'
  | 'UNSUPPORTED_CREDENTIAL';

/**
 * Claims the platform cannot stand behind.
 *
 * "Certified", "licensed" and "insured" are not vanity words — a customer
 * choosing between two providers reads them as facts the marketplace has
 * checked. Until verification can actually evidence them, a provider typing
 * them into a free-text box is making a claim on our behalf that nobody
 * verified. They become available when the evidence does.
 */
const CREDENTIAL_CLAIMS = [
  'certified',
  'licensed',
  'license',
  'insured',
  'accredited',
  'registered',
  'guaranteed',
  'مرخص',
  'مرخّص',
  'معتمد',
  'مؤمن',
  'مضمون',
];

/** Superlatives nobody can substantiate and every competitor can also type. */
const PROHIBITED_CLAIMS = [
  'best',
  'cheapest',
  'number one',
  'no.1',
  'no1',
  '#1',
  'official',
  'الأفضل',
  'الأرخص',
  'الأول',
  'رسمي',
];

// Deliberately broad. A title has no legitimate reason to contain a link, an
// email or a phone number: every one of those is an attempt to move the
// customer off-platform before the platform can protect either party.
const URL_PATTERN = /(https?:\/\/|www\.|\.(com|net|org|io|co|me|sy|ae|sa)\b)/i;
const EMAIL_PATTERN = /[\w.+-]+@[\w-]+\.[\w.]+/;
// Seven or more digits, ignoring the separators people put in numbers.
const PHONE_PATTERN = /(?:\+?\d[\s\-().]*){7,}/;
// Arabic-Indic digits, for the same reason.
const ARABIC_DIGITS_PATTERN = /(?:[٠-٩][\s\-().]*){7,}/;

export type TitleVerdict = { ok: true } | { ok: false; code: TitleRefusal };

/**
 * Is this title publishable?
 *
 * Shared so the form can say why before a round trip and the server can refuse
 * regardless — the form is a courtesy, the server is the rule. Order matters
 * only for which message is shown first; each check is independent.
 */
export function validateProfessionalTitle(raw: string): TitleVerdict {
  const value = raw.trim();

  if (value.length < TITLE_MIN_LENGTH) return { ok: false, code: 'TOO_SHORT' };
  if (value.length > TITLE_MAX_LENGTH) return { ok: false, code: 'TOO_LONG' };

  if (URL_PATTERN.test(value)) return { ok: false, code: 'CONTAINS_URL' };
  if (EMAIL_PATTERN.test(value) || PHONE_PATTERN.test(value) || ARABIC_DIGITS_PATTERN.test(value)) {
    return { ok: false, code: 'CONTAINS_CONTACT' };
  }

  const lowered = value.toLowerCase();
  // Word-ish matching for the Latin terms so "Best" is caught and "Bestway"
  // is not; the Arabic terms are matched as substrings because Arabic
  // morphology attaches prefixes that a word boundary would miss.
  if (CREDENTIAL_CLAIMS.some((term) => containsTerm(lowered, term))) {
    return { ok: false, code: 'UNSUPPORTED_CREDENTIAL' };
  }
  if (PROHIBITED_CLAIMS.some((term) => containsTerm(lowered, term))) {
    return { ok: false, code: 'PROHIBITED_CLAIM' };
  }

  return { ok: true };
}

function containsTerm(loweredValue: string, term: string): boolean {
  // Non-Latin terms have no usable word boundary in JS regex.
  if (!/^[a-z0-9.#\s]+$/.test(term)) return loweredValue.includes(term);
  const escaped = term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(`(^|[^a-z0-9])${escaped}([^a-z0-9]|$)`, 'i').test(loweredValue);
}
